---
- name: Configuring a nginx webserver and hosting a webpage on it
  hosts: nginx
  become: true
  vars_files:
    - user_auth.yml
  tasks:
    - name: Configuring a nginx webserver
      include_role: 
        name: nginx-server
