---
- name: Installing a required packages
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ pkgs }}"

- block:
    - name: "Installing a cryptography module"
      ansible.builtin.pip:
        name: "{{ item }}" 
      loop:
        - cryptography
        - passlib

    - name: "Generating a private key for the {{ server_name }}"
      community.crypto.openssl_privatekey:
        path: "{{ ssl_key }}"
        mode: "0640"
        type: RSA
        size: 2048
        state: present
  
    - name: "Generating a Certificate Signing Request(CSR) for self signed certificate"
      community.crypto.openssl_csr_pipe:
        privatekey_path: "{{ ssl_key }}"
        common_name: "{{ cert_common_name }}"
        organization_name: "{{ cert_org_name }}"
      register: csr

    - name: "Generating a self-signed certificate for {{ cert_common_name }}"
      community.crypto.x509_certificate:
        path: "{{ ssl_crt }}"
        privatekey_path: "{{ ssl_key }}"
        csr_content: "{{ csr.csr }}"
        provider: selfsigned
        selfsigned_not_after: "+365d" 
        mode: "0644"
        state: present
  when: ssl is defined and ssl | lower == "yes"

- name: "Preparing the configuration file for {{ cert_common_name }}"
  template:
    src: "{{ cert_org_name }}.conf.j2"
    dest: /etc/nginx/conf.d/{{ cert_org_name }}.conf

- name: "Ensuring the document root exists"
  file:
    path: "{{ doc_root }}"
    state: directory
    mode: "0755"

- name: Add a user to a password file and ensure permissions are set
  community.general.htpasswd:
    path: /etc/nginx/.htpasswd
    name: "{{ item.name }}"
    password: "{{  item.passwd }}"
    owner: root
    group: nginx
    mode: 0640
    crypt_scheme: md5_crypt
  loop: "{{ users }}"
  when: auth_enabled is defined and auth_enabled | lower == "yes"

- name: "Preparing the index page"
  template:
    src: ./index.html.j2
    dest: "{{ doc_root }}/index.html"
   
- name: CONFIGURING A SELINUX, FIREWALL AND SERVICES
  include_tasks: other.yml
    
